name: Create a package artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip the package
        run: |
          cd packages
          zip -qr ../sample-package.zip sample-package/*
          zip -qr ../sample-package2.zip sample-package2/*
          zip -qr ../sample-package3.zip sample-package3/*

      - name: Upload sample-package
        uses: actions/upload-artifact@v4
        with:
          name: sample-package
          path: sample-package.zip

      - name: Upload sample-package2
        uses: actions/upload-artifact@v4
        with:
          name: sample-package2
          path: sample-package2.zip

      - name: Upload sample-package3
        uses: actions/upload-artifact@v4
        with:
          name: sample-package3
          path: sample-package3.zip