name: Create a package artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip the package
        run: |
          cd ${{ vars.PACKAGE_DIR }}
          for dir in */ ; do
            zip -qr "../${dir%/}.zip" "$dir"
          done

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package artifacts
          path: '*.zip'